name: eclipse-core
recipe: laravel
env_file:
  - .env
config:
  webroot: vendor/eclipseapp/skeleton/public
  php: '8.2'
  via: nginx
  database: mariadb:10.6
services:
  appserver:
    type: php:custom
    overrides:
      image: slimdeluxe/php:8.2
  database:
    creds:
      database: eclipse
      user: developer
      password: developer
  mailhog:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver
  pma:
    type: phpmyadmin
    hosts:
      - database
    database:
      type: mariadb:10.6
proxy:
  mailhog:
    - mail.eclipse-core.lndo.site
  pma:
    - pma.eclipse-core.lndo.site
tooling:
  test:
    service: appserver
    description: Run package tests
    cmd: "vendor/bin/phpunit"
  testbench:
    service: appserver
    description: Execute testbench CLI
    cmd: "vendor/bin/testbench"
