<?php

namespace Eclipse\Core\Console\Commands;

use Eclipse\Core\Models\Package;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Storage;

class DiscoverPackages extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'eclipse:discover-packages {--test : Run the command in test mode}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Discover Eclipse packages from vendors';

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $dir = base_path('vendor');

        $this->info("Discovering Eclipse packages in $dir");

        $js_files = [];

        if (App::environment(['local', 'testing'])) {

            // Get composer.json data for current package
            $data = json_decode(file_get_contents('./composer.json'), true);

            // If we are testing an Eclipse package...
            if (stripos($data['name'], 'eclipseapp/') === 0 and $data['name'] !== 'eclipseapp/skeleton') {

                // ... insert own package record, since discovery process below only scans the vendor folder
                [$vendor, $name] = explode('/', $data['name']);
                $type = substr($data['extra']['eclipse']['type'], 0, 1);

                $package = Package::where([
                    'vendor' => $vendor,
                    'name' => $name,
                ])->first();

                if (empty($package)) {
                    $package = new Package();
                    $package->vendor = $vendor;
                    $package->name = $name;
                    $package->type = substr($data['extra']['eclipse']['type'], 0, 1);
                } elseif ($package->type !== $type) {
                    $package->type = $type;
                }

                $package->save();

                if (file_exists("./resources/js/$name.js")) {
                    // Add with path relative to the App skeleton JS that is in ./vendor/eclipseapp/skeleton/resources/js
                    $js_files[] = "../../../../../resources/js/$name.js";
                }
            }
        }

        foreach (File::directories($dir) as $vendor_dir) {
            foreach (File::directories($vendor_dir) as $package_dir) {

                if (! file_exists($package_dir.'/composer.json')) {
                    continue;
                }

                $json = json_decode(file_get_contents($package_dir.'/composer.json'), true);

                if (! isset($json['extra']['eclipse']['type'])) {
                    // Not an Eclipse package
                    continue;
                }

                $vendor = basename($vendor_dir);
                $name = basename($package_dir);
                $type = substr($json['extra']['eclipse']['type'], 0, 1);

                $package = Package::where([
                    'vendor' => $vendor,
                    'name' => $name,
                ])->first();

                if (empty($package)) {
                    $package = new Package;
                    $package->vendor = $vendor;
                    $package->name = $name;
                    $package->type = $type;
                    $package->save();
                    $this->line("Found new package: $vendor/$name");
                } elseif ($package->type !== $type) {
                    $package->type = $type;
                    $package->save();
                    $this->line("Updated package: $vendor/$name");
                }

                $js_file = "$package_dir/resources/js/$name.js";

                if (file_exists($js_file)) {
                    $js_files[] = $js_file;
                }
            }
        }

        // Write JS imports, but only if not running unit tests or if we are testing this command
        if (! App::runningUnitTests() || $this->option('test')) {
            $this->write_js_imports($js_files);
        }

        return 0;
    }

    private function write_js_imports(array $files): void
    {
        $lines = [
            '// This file is auto-generated by the Eclipse DiscoverPackages class.',
            '// To update the file, run the eclipse:discover-packages command.',
            '',
        ];

        foreach ($files as $file) {
            $lines[] = "import '$file';";
        }

        $lines[] = '';

        $target_file = ($this->option('test') ? 'test-' : '').'imports.js';

        Storage::disk('local')->put($target_file, implode("\n", $lines));

        $this->line("Successfully updated the app JS imports file in $target_file");
    }
}
